### ISSUE TITLE
[FR]: Add login validation & encription for clients

### ISSUE THREAD

**Issue by supercrafter333** [PocketCloudSystem/CloudSystem#2]
Hello,
Can you add login validation and encription for clients, please? (Verify Client(/Login)-Data, like UUID, SkindData,...)

That's very important for the security of this cloud-system.

**Comment by r3pt1s** [comment]
Why? The validation of the clientdata performs PocketMine and the packets are only accepted if the IP address of the client is the machine so localhost.
